// AUTO-GENERATED by `yarn tokens:build` from /tokens — do not edit by hand.
export const tokens = {
  "color": {
    "primary": {
      "main": "#1565c0"
    },
    "secondary": {
      "main": "#6d4c9f"
    },
    "success": {
      "main": "#2e7d32",
      "bg": "#edf7ed"
    },
    "error": {
      "main": "#c62828",
      "bg": "#fdecea"
    },
    "neutral": {
      "border": "#cfd8dc",
      "bg": "#f5f7f8"
    }
  },
  "space": {
    "xs": 4,
    "sm": 8,
    "md": 16,
    "lg": 24,
    "xl": 32
  },
  "radius": {
    "sm": 6,
    "md": 8
  },
  "font": {
    "family": {
      "base": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif"
    },
    "weight": {
      "regular": 400,
      "semibold": 600
    },
    "size": {
      "sm": "0.875rem",
      "md": "1rem",
      "lg": "1.25rem"
    }
  }
} as const;

export type Tokens = typeof tokens;
