// Generates design-token artifacts from the sources in /tokens:
//   - src/theme/tokens.ts   (typed nested object, consumed by the MUI theme)
//   - styles/tokens.css      (CSS custom properties, for non-MUI consumers)
//
// Run with `yarn tokens:build`. The generated files are committed so the rest of
// the build (Storybook, tsup, typecheck) never depends on running this first.
import StyleDictionary from 'style-dictionary';

// Custom format: a typed, nested `tokens` object built from token path + value.
StyleDictionary.registerFormat({
  name: 'ts/nested',
  format: ({ dictionary }) => {
    const root = {};
    for (const token of dictionary.allTokens) {
      let node = root;
      token.path.forEach((key, i) => {
        if (i === token.path.length - 1) node[key] = token.value;
        else node = node[key] ??= {};
      });
    }
    return (
      '// AUTO-GENERATED by `yarn tokens:build` from /tokens — do not edit by hand.\n' +
      `export const tokens = ${JSON.stringify(root, null, 2)} as const;\n\n` +
      'export type Tokens = typeof tokens;\n'
    );
  },
});

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'styles/',
      files: [{ destination: 'tokens.css', format: 'css/variables' }],
    },
    ts: {
      // No value transforms — the raw authored values flow straight through.
      // name/camel only makes token names unique (silences a collision warning);
      // the ts/nested format keys off token paths, not names.
      transforms: ['attribute/cti', 'name/camel'],
      buildPath: 'src/theme/',
      files: [{ destination: 'tokens.ts', format: 'ts/nested' }],
    },
  },
});

await sd.buildAllPlatforms();
